apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nl-query-agent-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hymaia/nl-query-agent
    targetRevision: main
    path: helm
    helm:
      values: |
        image:
          tag: "c7b70fd14d841fc841aea11b41f56c47124cee65"

  destination:
    server: https://kubernetes.default.svc
    namespace: nl-query-agent-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
