apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nl-query-agent-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hymaia/nl-query-agent
    targetRevision: main
    path: helm
    helm:
      values: |
        image:
          tag: "d0ade6df3d2f3ea3a4b8431e7b2c25dfd9cf2d80"

  destination:
    server: https://kubernetes.default.svc
    namespace: nl-query-agent-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
