apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nl-sql-agent-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<ORG>/repo-api
    targetRevision: main
    path: helm
    helm:
      values: |
        image:
          tag: "<IMAGE_TAG>"

  destination:
    server: https://kubernetes.default.svc
    namespace: nl-sql-agent-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
