# generated by terraform from infra/templates/values.yaml.tpl

nameOverride: ""
fullnameOverride: ""

image:
  repository: ${ecr_repository_url}
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  iamRoleArn: "${pod_iam_role_arn}"
  automountToken: true
  annotations: {}

aws:
  region: "${aws_region}"

bedrock:
  modelId: "${bedrock_model_id}"
  maxTokens: 4096

glue:
  database: "${glue_database}"

athena:
  outputBucket: "${athena_output_bucket}"
  workgroup: "${athena_workgroup}"

app:
  env: "production"
  logLevel: "INFO"

deployment:
  replicaCount: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  annotations: {}
  podAnnotations: {}
  podLabels: {}
  imagePullSecrets: []

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  extraEnv: []
  envFrom: []
  volumeMounts: []
  volumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  annotations: {}

ingress:
  enabled: true
  className: "alb"
  hosts:
    - "${ingress_host}"
  path: /*
  pathType: ImplementationSpecific
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
